AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'schema.rb'

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/MixinUsage:
  Exclude:
    - 'Rakefile'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20