language: ruby
rvm:
- 2.3
- 2.4
before_deploy:
- openssl aes-256-cbc -K $encrypted_eb3e4698194d_key -iv $encrypted_eb3e4698194d_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host $DEPLOY_SERVER\nStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
- provider: script
  skip_cleanup: false
  script:
    - /bin/bash --login ./deploy/development.sh
  on:
    branch: master
    rvm: '2.4'